#Application Name
spring:
  application:
    name: zuul-server     # This is the name for the remote configuration file
server:
  port: 8080 #the default port used for zuul service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    ordenes-service: # Service to create as sample
      path: /ordenes/** #path that will be intercepted
      serviceId: ordenes-service
      stripPrefix: true  #if zuul should replace the "/sample/" segment