spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: ordenes-service
  profiles:
    active: dev

server:
  port: 8020

KAFKA_BOOSTRAPADDRESS: ${HOST_IP_ADDRESS}:9192
GROUPID: order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${HOST_IP_ADDRESS}:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
